### ISSUE TITLE
Config set fails for type int

### ISSUE THREAD

**Issue by 0x6431346e** [ipfs/js-ipfs-http-client#881]
```
ipfs.config.set('Discovery.MDNS.Interval', 11, console.log)
ipfs.config.set('Discovery.MDNS.Interval', '11', console.log)
```
Both of these fail:

`cannot unmarshal string into Go struct field MDNS.Interval of type int`

Repro: https://github.com/0x6431346e/config-set-repro/blob/master/index.js

**Comment by koalalorenzo** [comment]
@alanshaw any update?

**Comment by koalalorenzo** [comment]
@alanshaw any news? This is preventing us from providing MDNS settings in [Siderus Orion](https://orion.siderus.io)

**Comment by koalalorenzo** [comment]
This is still present in the latest release `31.0.0`. Any plan? (sorry for insisting but this is blocking us)

**Comment by alanshaw** [comment]
Fixed in `31.0.1`

**Comment by mhjadav-plivo** [comment]
Upgraded dependencies but still getting one error looks like it's related to casting data we are passing

<img width="1680" alt="Screenshot 2019-05-22 at 6 38 38 PM" src="https://user-images.githubusercontent.com/45141126/58229995-bdff6d80-7d50-11e9-8fff-324c3b574f4c.png">
